spring.application.name=gamestore

## Configurar o Banco de Dados
spring.datasource.url=jdbc:postgresql://dpg-d6tvgfndiees73d7csm0-a:5432/db_deploy_gs_lpmalosso
spring.datasource.username=db_deploy_gs_lpmalosso_user
spring.datasource.password=s4mRGZmmpbb7ZRQ4YF7NfIpsngBUzeJq
## OBS: Nunca colocar senhas em documentos que vão para o github

## Configurações do JPA - hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true